### ISSUE TITLE
RxJava에 대해 잘 배웠어요!

### ISSUE THREAD

**Issue by minhyuuk** [ckrudals/RxJava_Kotlin_Src#1]
저도 저 책 읽고 싶었는데 시간이 없어서 읽지 못했습니다. 덕분에 짧은 시간에 좋은 내용을 요약할 수 있었습니다. 그리고 프사가 참 마음에 듭니다.

**Comment by ckrudals** [comment]
감사합니다. 더욱더 도움이 되도록 정리해보겠습니다!  프사도 혹시 필요하시면 보내드리도록 하겠습니다
